import api from '../api.js';

export const createSubmission = (data) => api.post('/student/submissions', data);
export const getSubmissions = () => api.get('/student/submissions');
export const getStudentSubmissions = () => api.get('/student/submissions');
export const getSubmission = (id) => api.get(`/student/submissions/${id}`);
export const getStudentDashboard = () => api.get('/student/dashboard');
export const getStudentPerformance = (params) => api.get('/student/performance', { params });
export const getStudentLeaderboard = (params) => api.get('/student/leaderboard', { params });
export const getStudentProblems = () => api.get('/student/problems');
export const getStudentProblem = (id) => api.get(`/student/problems/${id}`);
export const runStudentProblem = (id, data) => api.post(`/student/problems/${id}/run`, data);
export const runStudentTests = (id, data) => api.post(`/student/problems/${id}/run-tests`, data);
export const runFreeConsoleCode = (data) => api.post('/student/console/run', data);
export const getStudentCollections = (params) => api.get('/student/collections', { params });
export const getStudentTraining = () => api.get('/student/collections/training');
export const getStudentCollectionTopics = (collectionId, params) => api.get(`/student/collections/${collectionId}/topics`, { params });
export const getStudentTopic = (topicId) => api.get(`/student/topics/${topicId}`);
export const getStudentTopicProblems = (topicId, params) => api.get(`/student/topics/${topicId}/problems`, { params });
export const getStudentNextPracticeProblem = (params) => api.get('/student/practice/next', { params });
